USE ktp;

-- Load Committee table
INSERT INTO Committee (name) VALUES ('Membership');
INSERT INTO Committee (name) VALUES ('Marketing');
INSERT INTO Committee (name) VALUES ('Engagement');
INSERT INTO Committee (name) VALUES ('Fundraising');
INSERT INTO Committee (name) VALUES ('Professional Development');
INSERT INTO Committee (name) VALUES ('Technical Development');

-- Load Family table
INSERT INTO Family (name) VALUES ('Donatellos');
INSERT INTO Family (name) VALUES ('Honey Badgers');
INSERT INTO Family (name) VALUES ('Midnights');
INSERT INTO Family (name) VALUES ('Johnsons');

-- Load MemberStatus table
INSERT INTO MemberStatus (name) VALUES ('Active');
INSERT INTO MemberStatus (name) VALUES ('Inactive');
INSERT INTO MemberStatus (name) VALUES ('Probation');
INSERT INTO MemberStatus (name) VALUES ('Eboard');
INSERT INTO MemberStatus (name) VALUES ('Pledge');
INSERT INTO MemberStatus (name) VALUES ('Alumnus');

-- Load MemberRole table
INSERT INTO MemberRole (name) VALUES ('Member');
INSERT INTO MemberRole (name) VALUES ('Alumnus');
INSERT INTO MemberRole (name) VALUES ('Pledge');
INSERT INTO MemberRole (name) VALUES ('President');
INSERT INTO MemberRole (name) VALUES ('Vice President');
INSERT INTO MemberRole (name) VALUES ('Treasurer');
INSERT INTO MemberRole (name) VALUES ('Secretary');
INSERT INTO MemberRole (name) VALUES ('Director of Membership');
INSERT INTO MemberRole (name) VALUES ('Director of Marketing');
INSERT INTO MemberRole (name) VALUES ('Director of Engagement');
INSERT INTO MemberRole (name) VALUES ('Director of Professional Development');
INSERT INTO MemberRole (name) VALUES ('Director of Technology');

-- Load Term table
INSERT INTO Term (name) VALUES ('Winter');
INSERT INTO Term (name) VALUES ('Spring');
INSERT INTO Term (name) VALUES ('Summer');
INSERT INTO Term (name) VALUES ('Fall');

-- Load Semester table
INSERT INTO Semester (year, term_id) SELECT 2012, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2012, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2012, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2012, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2013, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2013, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2013, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2013, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2014, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2014, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2014, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2014, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2015, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2015, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2015, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2015, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2016, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2016, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2016, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2016, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2017, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2017, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2017, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2017, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2018, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2018, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2018, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2018, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2019, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2019, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2019, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2019, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2020, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2020, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2020, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2020, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2021, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2021, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2021, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2021, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2022, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2022, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2022, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2022, id FROM Term WHERE name = 'Fall';
INSERT INTO Semester (year, term_id) SELECT 2023, id FROM Term WHERE name = 'Winter';
INSERT INTO Semester (year, term_id) SELECT 2023, id FROM Term WHERE name = 'Spring';
INSERT INTO Semester (year, term_id) SELECT 2023, id FROM Term WHERE name = 'Summer';
INSERT INTO Semester (year, term_id) SELECT 2023, id FROM Term WHERE name = 'Fall';
-- Add more as needed

-- Load PledgeClass table
INSERT INTO PledgeClass (name, semester_id) SELECT 'Alpha',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2012 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Beta',      Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2012 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Gamma',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2013 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Delta',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2013 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Epsilon',	Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2014 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Zeta',      Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2014 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Eta',       Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2015 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Theta',     Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2015 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Iota',      Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2016 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Kappa',     Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2016 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Lambda',	Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2017 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Mu',        Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2017 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Nu',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2018 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Xi',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2018 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Omicron',	Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2019 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Pi',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2019 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Rho',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2020 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Sigma',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2020 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Tau',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2021 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Upsilon',	Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2021 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Phi',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2022 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Chi',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2022 AND Term.name = 'Fall';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Psi',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2023 AND Term.name = 'Winter';
INSERT INTO PledgeClass (name, semester_id) SELECT 'Omega',	    Semester.id FROM Semester JOIN Term ON Semester.term_id = Term.id WHERE Semester.year = 2023 AND Term.name = 'Fall';
-- Add more as needed

-- Load EventCategory table
INSERT INTO EventCategory (name) VALUES ('Other');
INSERT INTO EventCategory (name) VALUES ('Chapter');
INSERT INTO EventCategory (name) VALUES ('Rush');
INSERT INTO EventCategory (name) VALUES ('Social');
INSERT INTO EventCategory (name) VALUES ('Professional Development');
INSERT INTO EventCategory (name) VALUES ('Technical');
INSERT INTO EventCategory (name) VALUES ('Community Service');
INSERT INTO EventCategory (name) VALUES ('Family');
INSERT INTO EventCategory (name) VALUES ('External');

-- Load Major table
INSERT INTO Major (name) VALUES ('Actuarial Mathematics');
INSERT INTO Major (name) VALUES ('Aerospace Engineering');
INSERT INTO Major (name) VALUES ('Afroamerican and African Studies');
INSERT INTO Major (name) VALUES ('American Culture');
INSERT INTO Major (name) VALUES ('Ancient Near Eastern Studies');
INSERT INTO Major (name) VALUES ('Anthropology');
INSERT INTO Major (name) VALUES ('Arabic Studies');
INSERT INTO Major (name) VALUES ('Architecture');
INSERT INTO Major (name) VALUES ('Armenian Studies');
INSERT INTO Major (name) VALUES ('Art and Design');
INSERT INTO Major (name) VALUES ('Arts and Ideas in the Humanities');
INSERT INTO Major (name) VALUES ('Asian Studies');
INSERT INTO Major (name) VALUES ('Astronomy and Astrophysics');
INSERT INTO Major (name) VALUES ('Athletic Training');
INSERT INTO Major (name) VALUES ('Biochemistry');
INSERT INTO Major (name) VALUES ('Biology');
INSERT INTO Major (name) VALUES ('Biomedical Engineering');
INSERT INTO Major (name) VALUES ('Biomolecular Science');
INSERT INTO Major (name) VALUES ('Biophysics');
INSERT INTO Major (name) VALUES ('Biopsychology, Cognition, and Neuroscience');
INSERT INTO Major (name) VALUES ('Business');
INSERT INTO Major (name) VALUES ('Cell and Molecular Biology');
INSERT INTO Major (name) VALUES ('Cell and Molecular Biology and Biomedical Engineering');
INSERT INTO Major (name) VALUES ('Chemical Engineering');
INSERT INTO Major (name) VALUES ('Chemical Science');
INSERT INTO Major (name) VALUES ('Civil Engineering');
INSERT INTO Major (name) VALUES ('Classical Archaeology');
INSERT INTO Major (name) VALUES ('Classical Civilization');
INSERT INTO Major (name) VALUES ('Classical Languages and Literatures');
INSERT INTO Major (name) VALUES ('Cognitive Science');
INSERT INTO Major (name) VALUES ('Communication Studies');
INSERT INTO Major (name) VALUES ('Comparative Literature');
INSERT INTO Major (name) VALUES ('Computer Engineering');
INSERT INTO Major (name) VALUES ('Computer Science (BS)');
INSERT INTO Major (name) VALUES ('Computer Science (BSE)');
INSERT INTO Major (name) VALUES ('Creative Writing and Literature');
INSERT INTO Major (name) VALUES ('Dance');
INSERT INTO Major (name) VALUES ('Data Science (BS)');
INSERT INTO Major (name) VALUES ('Data Science (BSE)');
INSERT INTO Major (name) VALUES ('Dental Hygiene');
INSERT INTO Major (name) VALUES ('Drama');
INSERT INTO Major (name) VALUES ('Earth and Environmental Sciences');
INSERT INTO Major (name) VALUES ('Earth System Science and Engineering');
INSERT INTO Major (name) VALUES ('Ecology and Evolutionary Biology');
INSERT INTO Major (name) VALUES ('Economics');
INSERT INTO Major (name) VALUES ('Electrical Engineering');
INSERT INTO Major (name) VALUES ('Elementary Teacher Education');
INSERT INTO Major (name) VALUES ('Engineering Physics');
INSERT INTO Major (name) VALUES ('English');
INSERT INTO Major (name) VALUES ('Environment');
INSERT INTO Major (name) VALUES ('Environmental Engineering');
INSERT INTO Major (name) VALUES ('Evolutionary Anthropology');
INSERT INTO Major (name) VALUES ('Financial Mathematics');
INSERT INTO Major (name) VALUES ('French and Francophone Studies');
INSERT INTO Major (name) VALUES ('General Biology');
INSERT INTO Major (name) VALUES ('General Studies');
INSERT INTO Major (name) VALUES ('German');
INSERT INTO Major (name) VALUES ('Greek (Ancient) Language and Literature');
INSERT INTO Major (name) VALUES ('Greek (Modern) Language and Culture');
INSERT INTO Major (name) VALUES ('Health and Fitness');
INSERT INTO Major (name) VALUES ('Hebrew Studies');
INSERT INTO Major (name) VALUES ('History');
INSERT INTO Major (name) VALUES ('History of Art');
INSERT INTO Major (name) VALUES ('Individual Major Program');
INSERT INTO Major (name) VALUES ('Industrial and Operations Engineering');
INSERT INTO Major (name) VALUES ('Informatics');
INSERT INTO Major (name) VALUES ('Information');
INSERT INTO Major (name) VALUES ('Interarts Performance');
INSERT INTO Major (name) VALUES ('Interdisciplinary Astronomy');
INSERT INTO Major (name) VALUES ('Interdisciplinary Chemical Sciences');
INSERT INTO Major (name) VALUES ('Interdisciplinary Physics');
INSERT INTO Major (name) VALUES ('International Studies');
INSERT INTO Major (name) VALUES ('Italian');
INSERT INTO Major (name) VALUES ('Jazz Studies');
INSERT INTO Major (name) VALUES ('Judaic Studies');
INSERT INTO Major (name) VALUES ('Latin American and Caribbean Studies');
INSERT INTO Major (name) VALUES ('Latin Language and Literature');
INSERT INTO Major (name) VALUES ('Latina/o Studies');
INSERT INTO Major (name) VALUES ('Linguistics');
INSERT INTO Major (name) VALUES ('Materials Science and Engineering');
INSERT INTO Major (name) VALUES ('Mathematical Sciences');
INSERT INTO Major (name) VALUES ('Mathematics');
INSERT INTO Major (name) VALUES ('Mechanical Engineering');
INSERT INTO Major (name) VALUES ('Microbiology');
INSERT INTO Major (name) VALUES ('Middle Eastern and North African Studies');
INSERT INTO Major (name) VALUES ('Movement Science');
INSERT INTO Major (name) VALUES ('Multidisciplinary Music Studies');
INSERT INTO Major (name) VALUES ('Music (Non-Professional)');
INSERT INTO Major (name) VALUES ('Music Composition');
INSERT INTO Major (name) VALUES ('Music Education');
INSERT INTO Major (name) VALUES ('Music Performance');
INSERT INTO Major (name) VALUES ('Music Performance with Teacher Certification');
INSERT INTO Major (name) VALUES ('Musical Theatre');
INSERT INTO Major (name) VALUES ('Musicology');
INSERT INTO Major (name) VALUES ('Naval Architecture and Marine Engineering');
INSERT INTO Major (name) VALUES ('Near Eastern Studies');
INSERT INTO Major (name) VALUES ('Neuroscience');
INSERT INTO Major (name) VALUES ('Nuclear Engineering and Radiological Sciences');
INSERT INTO Major (name) VALUES ('Nursing');
INSERT INTO Major (name) VALUES ('Nursing—Second Career');
INSERT INTO Major (name) VALUES ('Organizational Studies');
INSERT INTO Major (name) VALUES ('Performing Arts Technology');
INSERT INTO Major (name) VALUES ('Persian Studies');
INSERT INTO Major (name) VALUES ('Pharmaceutical Sciences');
INSERT INTO Major (name) VALUES ('Philosophy');
INSERT INTO Major (name) VALUES ('Philosophy, Politics, and Economics');
INSERT INTO Major (name) VALUES ('Physics');
INSERT INTO Major (name) VALUES ('Plant Biology');
INSERT INTO Major (name) VALUES ('Polish');
INSERT INTO Major (name) VALUES ('Political Science');
INSERT INTO Major (name) VALUES ('Psychology');
INSERT INTO Major (name) VALUES ('Public Policy');
INSERT INTO Major (name) VALUES ('Pure Mathematics');
INSERT INTO Major (name) VALUES ('RC Individual Major Program');
INSERT INTO Major (name) VALUES ('Romance Languages and Literature');
INSERT INTO Major (name) VALUES ('Russian');
INSERT INTO Major (name) VALUES ('Russian, East European, and Eurasian Studies');
INSERT INTO Major (name) VALUES ('Screen Arts and Cultures');
INSERT INTO Major (name) VALUES ('Screenwriting');
INSERT INTO Major (name) VALUES ('Secondary Teacher Education');
INSERT INTO Major (name) VALUES ('Social Theory and Practice');
INSERT INTO Major (name) VALUES ('Sociology');
INSERT INTO Major (name) VALUES ('Sound Engineering');
INSERT INTO Major (name) VALUES ('Spanish');
INSERT INTO Major (name) VALUES ('Sport Management');
INSERT INTO Major (name) VALUES ('Statistics');
INSERT INTO Major (name) VALUES ('Theatre Arts');
INSERT INTO Major (name) VALUES ('Theatre Design and Production');
INSERT INTO Major (name) VALUES ('Theatre Performance (Acting and Directing)');
INSERT INTO Major (name) VALUES ('Turkish Studies');
INSERT INTO Major (name) VALUES ('Women’s Studies');

-- Load Minor table
INSERT INTO Minor (name) VALUES ('Afroamerican and African Studies');
INSERT INTO Minor (name) VALUES ('American Culture');
INSERT INTO Minor (name) VALUES ('Anthropology');
INSERT INTO Minor (name) VALUES ('Applied Statistics');
INSERT INTO Minor (name) VALUES ('Arab and Muslim American Studies');
INSERT INTO Minor (name) VALUES ('Art & Design');
INSERT INTO Minor (name) VALUES ('Asian Languages & Cultures');
INSERT INTO Minor (name) VALUES ('Asian Studies');
INSERT INTO Minor (name) VALUES ('Asian/Pacific Islander American Studies');
INSERT INTO Minor (name) VALUES ('Astronomy and Astrophysics');
INSERT INTO Minor (name) VALUES ('Biochemistry');
INSERT INTO Minor (name) VALUES ('Biological Anthropology');
INSERT INTO Minor (name) VALUES ('Biology');
INSERT INTO Minor (name) VALUES ('Biophysics');
INSERT INTO Minor (name) VALUES ('Bosnian/Croatian/Serbian Literature and Culture');
INSERT INTO Minor (name) VALUES ('Business');
INSERT INTO Minor (name) VALUES ('Central Eurasian Studies');
INSERT INTO Minor (name) VALUES ('Chemical Measurement Science');
INSERT INTO Minor (name) VALUES ('Chemical Physics');
INSERT INTO Minor (name) VALUES ('Chemistry');
INSERT INTO Minor (name) VALUES ('Classical Archaeology');
INSERT INTO Minor (name) VALUES ('Classical Civilization');
INSERT INTO Minor (name) VALUES ('Climate and Space Sciences and Engineering');
INSERT INTO Minor (name) VALUES ('Community Action and Social Change (CASC)');
INSERT INTO Minor (name) VALUES ('Complex Systems');
INSERT INTO Minor (name) VALUES ('Computer Science');
INSERT INTO Minor (name) VALUES ('Creative Writing');
INSERT INTO Minor (name) VALUES ('Crime and Justice');
INSERT INTO Minor (name) VALUES ('Czech Language, Literature, and Culture');
INSERT INTO Minor (name) VALUES ('Design and Production');
INSERT INTO Minor (name) VALUES ('Digital Studies');
INSERT INTO Minor (name) VALUES ('Drama: Text-to-Performance (TtP)');
INSERT INTO Minor (name) VALUES ('Early Christian Studies');
INSERT INTO Minor (name) VALUES ('Earth Sciences');
INSERT INTO Minor (name) VALUES ('East European Studies');
INSERT INTO Minor (name) VALUES ('Eastern Europe, Cultures and Literatures of');
INSERT INTO Minor (name) VALUES ('Ecology and Evolutionary Biology (EEB)');
INSERT INTO Minor (name) VALUES ('Economics');
INSERT INTO Minor (name) VALUES ('Electrical Engineering');
INSERT INTO Minor (name) VALUES ('Energy and Science Policy');
INSERT INTO Minor (name) VALUES ('Entrepreneurship');
INSERT INTO Minor (name) VALUES ('Environment');
INSERT INTO Minor (name) VALUES ('Environmental Geology');
INSERT INTO Minor (name) VALUES ('Epistemology and Philosophy of Science');
INSERT INTO Minor (name) VALUES ('Food and the Environment');
INSERT INTO Minor (name) VALUES ('French and Francophone Studies');
INSERT INTO Minor (name) VALUES ('Gender and Health');
INSERT INTO Minor (name) VALUES ('Gender, Race, and Nation');
INSERT INTO Minor (name) VALUES ('General Philosophy');
INSERT INTO Minor (name) VALUES ('Geology');
INSERT INTO Minor (name) VALUES ('German Studies');
INSERT INTO Minor (name) VALUES ('Global History');
INSERT INTO Minor (name) VALUES ('Global Media Studies');
INSERT INTO Minor (name) VALUES ('Global Theatre and Ethnic Studies');
INSERT INTO Minor (name) VALUES ('Greek (Ancient) Language and Literature');
INSERT INTO Minor (name) VALUES ('Greek (Modern) Language and Culture');
INSERT INTO Minor (name) VALUES ('History');
INSERT INTO Minor (name) VALUES ('History of Art');
INSERT INTO Minor (name) VALUES ('History of Law and Policy');
INSERT INTO Minor (name) VALUES ('History of Medicine and Health');
INSERT INTO Minor (name) VALUES ('History of Philosophy');
INSERT INTO Minor (name) VALUES ('Interdisciplinary Astronomy');
INSERT INTO Minor (name) VALUES ('Intergroup Relations Education');
INSERT INTO Minor (name) VALUES ('International Studies');
INSERT INTO Minor (name) VALUES ('Islamic Studies');
INSERT INTO Minor (name) VALUES ('Italian');
INSERT INTO Minor (name) VALUES ('Judaic Studies');
INSERT INTO Minor (name) VALUES ('Latin American and Caribbean Studies');
INSERT INTO Minor (name) VALUES ('Latin Language and Literature');
INSERT INTO Minor (name) VALUES ('Latino/a Studies');
INSERT INTO Minor (name) VALUES ('Law, Justice, and Social Change');
INSERT INTO Minor (name) VALUES ('Lesbian, Gay, Bisexual, Transgender, Queer (LGBTQ) and Sexuality Studies');
INSERT INTO Minor (name) VALUES ('Linguistics');
INSERT INTO Minor (name) VALUES ('Mathematics');
INSERT INTO Minor (name) VALUES ('Medical Anthropology');
INSERT INTO Minor (name) VALUES ('Medieval and Early Modern Studies');
INSERT INTO Minor (name) VALUES ('Mind and Meaning');
INSERT INTO Minor (name) VALUES ('Modern European Studies');
INSERT INTO Minor (name) VALUES ('Modern Middle Eastern and North African Studies');
INSERT INTO Minor (name) VALUES ('Moral and Political Philosophy');
INSERT INTO Minor (name) VALUES ('Multidisciplinary Design');
INSERT INTO Minor (name) VALUES ('Museum Studies');
INSERT INTO Minor (name) VALUES ('Music');
INSERT INTO Minor (name) VALUES ('Native American Studies');
INSERT INTO Minor (name) VALUES ('Near Eastern Languages and Cultures');
INSERT INTO Minor (name) VALUES ('Oceanography');
INSERT INTO Minor (name) VALUES ('Paleontology');
INSERT INTO Minor (name) VALUES ('Peace and Social Justice (PSJ)');
INSERT INTO Minor (name) VALUES ('Performing Arts Management');
INSERT INTO Minor (name) VALUES ('Physics');
INSERT INTO Minor (name) VALUES ('Plant Biology');
INSERT INTO Minor (name) VALUES ('Polish Language, Literature, and Culture');
INSERT INTO Minor (name) VALUES ('Political Science');
INSERT INTO Minor (name) VALUES ('Polymer Chemistry');
INSERT INTO Minor (name) VALUES ('Portuguese');
INSERT INTO Minor (name) VALUES ('Religion');
INSERT INTO Minor (name) VALUES ('Russian Language, Literature, and Culture');
INSERT INTO Minor (name) VALUES ('Russian Studies');
INSERT INTO Minor (name) VALUES ('Scandinavian Studies');
INSERT INTO Minor (name) VALUES ('Science, Technology and Society (STS)');
INSERT INTO Minor (name) VALUES ('Spanish Language, Literature, and Culture');
INSERT INTO Minor (name) VALUES ('Statistics');
INSERT INTO Minor (name) VALUES ('Sustainability');
INSERT INTO Minor (name) VALUES ('Translation Studies');
INSERT INTO Minor (name) VALUES ('Ukrainian Language, Literature, and Culture');
INSERT INTO Minor (name) VALUES ('Urban Studies');
INSERT INTO Minor (name) VALUES ('Writing');
INSERT INTO Minor (name) VALUES ('Yiddish Studies');
INSERT INTO Minor (name) VALUES ('International Minor for Engineers');
INSERT INTO Minor (name) VALUES ('Environmental Engineering');
INSERT INTO Minor (name) VALUES ('Naval Engineering');
INSERT INTO Minor (name) VALUES ('Program in Sustainable Engineering (PISE)');
INSERT INTO Minor (name) VALUES ('Program in Entrepreneurship');


